trigger:
- master

jobs:
  - job: BuildAndTest
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.15.x'
        inputs:
          versionSpec: '10.15.x'
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          command: 'install'
          verbose: false
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
      - script: 'npm run test'
        displayName: 'Run tests'
        env:
          DISPLAY: :10
      - task: PublishCodeCoverageResults@1
        inputs: 
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
          reportDirectory: '$(Build.SourcesDirectory)/coverage'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.SourcesDirectory)
  - job: Release
    dependsOn: 
      - BuildAndTest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0  
        displayName: 'Use Node 10.15.x'
        inputs:
          versionSpec: '10.15.x'
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'Install vsce'
        inputs:
          command: custom
          customCommand: 'install -g vsce'
      - script: vsce publish -p $(PUBLISH_KEY)
        displayName: 'Publish Extension'
