trigger:
- master

jobs:
  - job: Windows
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.15.x'
        inputs:
          versionSpec: '10.15.x'
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'Run Tests'
        inputs:
          command: custom
          customCommand: 'run test'
  - job: macOS
    pool:
      name: Hosted macOS
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.15.x'
        inputs:
          versionSpec: '10.15.x'
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'Run Tests'
        inputs:
          command: custom
          customCommand: 'run test'
  - job: Linux
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.15.x'
        inputs:
          versionSpec: '10.15.x'
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
      - script: 'npm run test'
        displayName: 'Run tests'
        env:
          DISPLAY: :10
  - job: Release
    dependsOn: 
      - Linux
      - Windows
      - macOS
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 10.15.x'
        inputs:
          versionSpec: '10.15.x'
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
      - task: Npm@1
        displayName: 'Install vsce'
        inputs:
          command: custom
          customCommand: 'install -g vsce'
      - script: 'vsce publish -p ${PUBLISH_KEY}'
        displayName: 'Release'
