const languages: { [name: string]: string } = {
    "abap": "ABAP",
    "bat": "Windows Bat",
    "bibtex": "BibTeX",
    "clojure": "Clojure",
    "coffeescript": "Coffeescript",
    "c": "C",
    "cpp": "C++",
    "csharp": "C#",
    "css": "CSS",
    "diff": "Diff",
    "dockerfile": "Dockerfile",
    "fsharp": "F#",
    "git-commit and git-rebase": "Git",
    "go": "Go",
    "groovy": "Groovy",
    "handlebars": "Handlebars",
    "hcl": "HCL",
    "html": "HTML",
    "ini": "Ini",
    "java": "Java",
    "javascript": "JavaScript",
    "javascriptreact": "React (JavaScript)",
    "json": "JSON",
    "jsonc": "JSON with Comments",
    "latex": "LaTeX",
    "less": "Less",
    "lua": "Lua",
    "makefile": "Makefile",
    "markdown": "Markdown",
    "objective-c": "Objective-C",
    "objective-cpp": "Objective-C++",
    "perl": "Perl",
    "perl6": "Perl",
    "php": "PHP",
    "plaintext": "Plain Text",
    "powershell": "Powershell",
    "jade": "Pug",
    "python": "Python",
    "r": "R",
    "razor": "Razor (cshtml)",
    "ruby": "Ruby",
    "rust": "Rust",
    "scss": "SCSS",
    "sass": "SASS",
    "shaderlab": "ShaderLab",
    "shellscript": "Shell Script",
    "sql": "SQL",
    "swift": "Swift",
    "typescript": "TypeScript",
    "typescriptreact": "React (TypeScript)",
    "tex": "TeX",
    "vb": "Visual Basic",
    "vue": "Vue",
    "xml": "XML",
    "xsl": "XSL",
    "yaml": "YAML"
};

export default languages;